name: Destroy using Terraform

on:
  push:
    branches:
      - develop
      - main

env:
  terraform_version: 1.3.3
  terraform_workdir: infra-as-code/terraform
  terraform_backend_file: backend.tfvars
  terraform_provider_file: provider.tfvars
  terraform_action: ${{ secrets.TERRAFORM_ACTION }}
  gcp_credential_file: gcp_service_account.json

jobs:
  cleanup:
    name: Destroy infrastructure using Terraform
    if: ${{ env.terraform_action == 'destroy' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.terraform_workdir }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Retrieve the secret and decode it to a file
        env:
          terraform_backend_tfvars: ${{ secrets.TERRAFORM_BACKEND_TFVARS }}
          terraform_provider_tfvars: ${{ secrets.TERRAFORM_PROVIDER_TFVARS }}
          gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
          echo $terraform_backend_tfvars | base64 --decode > $terraform_backend_file
          echo $terraform_provider_tfvars | base64 --decode > $terraform_provider_file
          echo $gcp_service_account | base64 --decode > $gcp_credential_file

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -input=false \
            -backend-config=$terraform_backend_file

      - name: Terraform Destroy
        id: destroy
        run: |
          terraform destroy \
            -input=false \
            -auto-approve \
            -var-file=$terraform_provider_file